### ISSUE TITLE
I don't like Dallin. Can we get rid of him? 

### ISSUE THREAD

**Issue by mikechi4** [you-tube-group/you-tube-clone#42]

**Comment by dallin-r-parker** [comment]
sure that's probably for the best.

**Comment by otteb** [comment]
Yeah I'm still bitter about those patriots... #Seahawks4life!

**Comment by joeblank** [comment]
Not till the home view is done, or we are screwed

**Comment by semoog** [comment]
Dallin is staying. Get over it you babies
